version: '3.8'

services:
  vortex:
    build: .
    ports:
      - "8000:8000"
    networks:
      - vortex-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - vortex-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana:/var/lib/grafana/dashboards
    networks:
      - vortex-net

networks:
  vortex-net:
    driver: bridge
