{
 "title": "Vortex Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vortex_active_nodes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(vortex_requests_total[1m])",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "rate(vortex_requests_total{status=~\"5.*\"}[1m])",
     "legendFormat": "5xx Errors"
    }
   ]
  }
 ]
}